"""add sort_order to schools

Revision ID: 9e3c6dafb3dc
Revises: f2a0d532a8d8
Create Date: 2026-09-30 21:45:06.294776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3c6dafb3dc'
down_revision: Union[str, Sequence[str], None] = 'f2a0d532a8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHOOL_ORDER = {
    "chunghsing_high": 1,
    "nantou_high": 2,
    "other_high": 3,
    "university": 4,
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###

    # 正式環境四個學校的顯示順序：高中職排在一起，大學生放最後
    for code, order in SCHOOL_ORDER.items():
        op.execute(
            sa.text("UPDATE schools SET sort_order = :order WHERE join_link_code = :code").bindparams(
                order=order, code=code
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
