"""initial schema

Revision ID: ac155fd37126
Revises: 
Create Date: 2026-08-21 10:32:57.731852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac155fd37126'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_card_text', sa.Text(), nullable=False),
    sa.Column('knowledge_card_image_url', sa.String(length=500), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option', sa.String(length=200), nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('schools',
    sa.Column('school_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('join_link_code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_index(op.f('ix_schools_join_link_code'), 'schools', ['join_link_code'], unique=True)
    op.create_table('daily_pushes',
    sa.Column('push_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('push_id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('badges', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_students_line_user_id'), 'students', ['line_user_id'], unique=True)
    op.create_table('answer_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=200), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('assessment_responses',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assessment_round', sa.String(length=50), nullable=False),
    sa.Column('knowledge_score', sa.Integer(), nullable=False),
    sa.Column('action_responses', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('eco_checkins',
    sa.Column('checkin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('line_message_id', sa.String(length=100), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('image_mime', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('checkin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eco_checkins')
    op.drop_table('assessment_responses')
    op.drop_table('answer_logs')
    op.drop_index(op.f('ix_students_line_user_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('daily_pushes')
    op.drop_index(op.f('ix_schools_join_link_code'), table_name='schools')
    op.drop_table('schools')
    op.drop_table('questions')
    # ### end Alembic commands ###
