"""Add reviewed_by to eco_checkins

Revision ID: b5a7d02c67e2
Revises: 12040112f6c1
Create Date: 2026-08-27 13:57:18.766797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a7d02c67e2'
down_revision: Union[str, Sequence[str], None] = '12040112f6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eco_checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eco_checkins', schema=None) as batch_op:
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###
