"""add assessment_pushes table

Revision ID: f2a0d532a8d8
Revises: c3d9a1e5f7b2
Create Date: 2026-09-30 20:19:00.482906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a0d532a8d8'
down_revision: Union[str, Sequence[str], None] = 'c3d9a1e5f7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_pushes',
    sa.Column('push_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_round', sa.String(length=20), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('push_id')
    )
    with op.batch_alter_table('assessment_pushes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_pushes_assessment_round'), ['assessment_round'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_pushes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_pushes_assessment_round'))

    op.drop_table('assessment_pushes')
    # ### end Alembic commands ###
