"""assessment survey schema and student demographics

Revision ID: f65fb377526c
Revises: ac155fd37126
Create Date: 2026-08-21 16:37:58.145815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f65fb377526c'
down_revision: Union[str, Sequence[str], None] = 'ac155fd37126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responses', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_unique_constraint('uq_assessment_student_round', ['student_id', 'assessment_round'])
        batch_op.drop_column('action_responses')
        batch_op.drop_column('knowledge_score')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('grade')

    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_score', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('action_responses', sqlite.JSON(), nullable=False))
        batch_op.drop_constraint('uq_assessment_student_round', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('responses')

    # ### end Alembic commands ###
